config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  
  get 'signup', to: 'users#new'
  resources :users, only:[:show, :new, :create, :edit, :update]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :ambitions, only:[:show, :new, :create, :edit, :update, :destroy]
  
  get '/ambitions/:id/key_results/new', to: 'key_results#new'
  resources :key_results, only:[:create, :edit, :update, :destroy]
  
  get '/key_results/:id/daily_results/new', to: 'daily_results#new'
  resources :daily_results, only:[:create, :edit, :update, :destroy]
end

app/models/daily_result.rb
class DailyResult < ApplicationRecord
  belongs_to :key_result
  
  validates :result, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than: 500 }
  validates :result_date, presence: true, uniqueness: { scope: :key_result_id }
end

app/controllers/daily_results_controller.rb
class DailyResultsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:edit, :update, :destroy]

  def new
    @key_result = KeyResult.find(params[:id])
    @ambition = @key_result.ambition
    
    unless current_user.id == @ambition.user_id
      flash[:danger] = "権限がありません"
      redirect_to root_url
    end
    
    @daily_result = @key_result.daily_results.build
  end

  def create
    @key_result = KeyResult.find(params[:key_result_id])
    @ambition = @key_result.ambition
    @daily_result = @key_result.daily_results.build(daily_result_params)
    
    if @key_result.numerical_goal < @daily_result.result
      flash[:danger] = '評価値は目標数値より大きくしないでください'
      render :new
    elsif @ambition.start_date > @daily_result.result_date || @ambition.end_date <@daily_result.result_date
      flash[:danger] = '評価はObjectiveの期間内に行ってください'
      render :new
    elsif @daily_result.save
      flash[:success] = '評価の保存に成功しました'
      redirect_to @ambition
    else
      flash[:danger] = '評価の保存に失敗しました'
      render :new
    end
  end

  def edit
  end

  def update
    @result = params[:daily_result][:result].to_i
    
    if @key_result.numerical_goal < @result
      flash[:danger] = '評価値は目標数値より大きくしないでください'
      render :edit
    elsif @daily_result.update(daily_result_params)
      flash[:success] = '評価の変更に成功しました'
      redirect_to @ambition
    else
      flash[:danger] = '評価の変更に失敗しました'
      render :edit
    end
  end

  def destroy
    @daily_result.destroy
    flash[:success] = '評価履歴を削除しました'
    redirect_to @ambition
  end

  private 

  def daily_result_params
    params.require(:daily_result).permit(:result, :result_date)
  end

  def correct_user
    @daily_result = DailyResult.find(params[:id])
    @key_result = @daily_result.key_result
    @ambition = @key_result.ambition
    unless current_user.id == @ambition.user_id
      flash[:danger] = "権限がありません"
      redirect_to root_url
    end
  end
end

app/views/daily_results/_edit_form.html.erb
<%= form_with(model: daily_result, local: true) do |f| %>
<%= hidden_field_tag :key_result_id, daily_result.key_result.id %>
<%= hidden_field_tag :result_date, daily_result.result_date %>
<%= render 'layouts/error_messages', model: f.object %>


<div class="row">
  <div class="col-sm-5">
    <p>本日の達成度</p>
    <p>(半角数字)</p>
  </div>
  <div class="form-group col-sm-7">
    <%= f.number_field :result, class: 'form-control' %>
  </div>
</div>
<div class="row justify-content-center mb-5">
  <div class="col-4">
    <%= f.submit '評価', class: 'btn btn-primary btn-block' %>
  </div>
</div>
<% end %>

app/views/daily_results/_form.html.erb
<%= form_with(model: daily_result, local: true) do |f| %>
<%= hidden_field_tag :key_result_id, daily_result.key_result.id %>
<%= render 'layouts/error_messages', model: f.object %>

<div class="row">
  <div class="col-sm-5">
    <p>評価日時</p>
  </div>
  <div class="form-group col-sm-7">
    <%= f.date_select :result_date, use_month_numbers: true, start_year:Time.now.year-1, end_year:Time.now.year+10 %>
  </div>
</div>


<div class="row">
  <div class="col-sm-5">
    <p>本日の達成度</p>
    <p>(半角数字)</p>
  </div>
  <div class="form-group col-sm-7">
    <%= f.number_field :result, class: 'form-control' %>
  </div>
</div>
<div class="row justify-content-center mb-5">
  <div class="col-4">
    <%= f.submit '評価', class: 'btn btn-primary btn-block' %>
  </div>
</div>
<% end %>

app/views/daily_results/_index.html.erb
<table class="table table-bordered">
  <tr>
    <td>日付</td>
    <td>評価</td>
    <td>リンク</td>
  </tr>
  <% key_result.daily_results.order(result_date: :desc).each do |daily_result| %>
  <tr>
    <td>
      <%= daily_result.result_date %>
    </td>
    <td>
      <%= daily_result.result %>
    </td>
    <td>
      <%= link_to '評価値編集', edit_daily_result_path(daily_result) %>
    </td>
  </tr>
  <% end %>
</table>

app/views/daily_results/edit.html.erb
<div class="row pb-4 mb-3 border-bottom">
  <div class="col-sm-2">
    <%= link_to '戻る', ambition_path(@daily_result.key_result.ambition) %>
  </div>
  <div class="col-sm-8 text-center">
    <h2>Key Result評価履歴編集・削除</h2>
  </div>
  <div class="col-sm-2 text-center">
    <%= link_to '削除', daily_result_path, class: 'btn btn-danger btn-sm', method: :delete, data: { confirm: "本当に削除しますか？" } %>
  </div>
</div>

<%= @ambition.content %>
<%= @key_result.content %>
<div>
  <%= render 'edit_form', ambition: @ambition, key_result: @key_result, daily_result: @daily_result %>
</div>

app/views/daily_results/new.html.erb
<div class="text-center pb-4 mb-3 border-bottom">
  <h2>Key Result評価</h2>
</div>
<%= @ambition.content %>
<%= @key_result.content %>
<div>
  <%= render 'form', daily_result: @daily_result %>
</div>