config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  
  get 'signup', to: 'users#new'
  resources :users, only:[:show, :new, :create, :edit, :update]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :ambitions, only:[:show, :new, :create, :edit, :update, :destroy]
  
  get '/ambitions/:id/key_results/new', to: 'key_results#new'
  resources :key_results, only:[:create, :edit, :update, :destroy]
  
  get '/key_results/:id/daily_results/new', to: 'daily_results#new'
  resources :daily_results, only:[:create, :edit, :update, :destroy]
end

app/models/ambition.rb
class Ambition < ApplicationRecord
  belongs_to :user
  
  validates :content, presence: true, length: { maximum: 255 }
  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :start_date_before_end_date
  
  has_many :key_results, dependent: :destroy
  
  private
  
  def start_date_before_end_date
    if start_date >= end_date
      errors.add(:message, "終了日より開始日の日付を早くしてください")
    end
  end
end

app/controllers/ambitions_controller.rb
class AmbitionsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  
  def show
  end

  def new
    @ambition = current_user.ambitions.build
  end

  def create
    @ambition = current_user.ambitions.build(ambition_params)
    if @ambition.save
      flash[:success] = 'Objective作成に成功しました　一つ目のKRを作成しましょう'
      redirect_to "/ambitions/#{@ambition.id}/key_results/new"
    else
      flash[:danger] = 'Objective作成に失敗しました'
      render :new
    end
  end

  def edit
  end

  def update
    if @ambition.update(ambition_params)
      flash[:success] = 'Objectiveは正常に更新されました'
      redirect_to @ambition
    else
      flash[:danger] = 'Objectiveは更新されませんでした'
      render :edit
    end
  end

  def destroy
    
    @ambition.destroy
    flash[:success] = 'Objectiveを削除しました'
    redirect_to user_path(current_user)
  end
  
  private
  
  def ambition_params
    params.require(:ambition).permit(:content, :start_date, :end_date)
  end
  
  def correct_user
    @ambition = Ambition.find(params[:id])
    unless current_user.id == @ambition.user_id
      flash[:danger] = "権限がありません"
      redirect_to root_url
    end
  end
end

app/views/ambitions/_ambition_form.html.erb
<%= form_with(model: ambition, local: true) do |f| %>
<%= render 'layouts/error_messages', model: f.object %>
<div class="row">
  <div class="col-sm-4">
    <p>期間</p>
  </div>
  <div class="col-sm-8">
    <div class="form-group">
      <%= f.label :start_date, '開始日' %>
      <%= f.date_select :start_date, use_month_numbers: true, start_year:Time.now.year-1, end_year:Time.now.year+10 %>
    </div>
    <div class="form-group">
      <%= f.label :end_date, '終了日' %>
      <%= f.date_select :end_date, use_month_numbers: true, start_year:Time.now.year-1, end_year:Time.now.year+10 %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-4">
    <p>Objective</p>
  </div>
  <div class="col-sm-8 form-group">
    <%= f.text_area :content, class: 'form-control', rows: 6 %>
  </div>
</div>
<div class="text-center">
<%= f.submit '保存', class: 'btn btn-primary btn-lg' %>
</div>
<% end %>

app/views/ambitions/_form.html.erb
<%= form_with(model: ambition, local: true) do |f| %>
<%= render 'layouts/error_messages', model: f.object %>
<div class="row">
  <div class="col-sm-4">
    <p>期間</p>
  </div>
  <div class="col-sm-8">
    <div class="form-group">
      <%= f.label :start_date, '開始日' %>
      <%= f.date_select :start_date, use_month_numbers: true, start_year:Time.now.year-1, end_year:Time.now.year+10 %>
    </div>
    <div class="form-group">
      <%= f.label :end_date, '終了日' %>
      <%= f.date_select :end_date, use_month_numbers: true, start_year:Time.now.year-1, end_year:Time.now.year+10 %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-4">
    <p>Objective</p>
  </div>
  <div class="col-sm-8 form-group">
    <%= f.text_area :content, class: 'form-control', rows: 6 %>
  </div>
</div>
<div class="row justify-content-center mb-5">
  <div class="col-4">
    <%= f.submit '保存', class: 'btn btn-primary btn-block' %>
  </div>
</div>
<% end %>

app/views/ambitions/_index.html.erb
<% ambitions.each do |ambition| %>
<div class="card mb-3">
  <div class="card">
    <div class="text-center card-header font-weight-bold">
      <%= link_to ambition.content, ambition_path(ambition), class: 'text-dark border-bottom' %>
    </div>
    <div class="text-center card-body">
      <%= ambition.start_date %> 〜 <%= ambition.end_date %>
    </div>
  </div>
</div>
<% end %>

<%= paginate ambitions %>

app/views/ambitions/edit.html.erb
<div class="text-center pb-4 mb-3 border-bottom">
  <h2>Objective編集</h2>
</div>

<div>
  <%= render 'form', ambition: @ambition %>
</div>

app/views/ambitions/new.html.erb
<div class="text-center pb-4 mb-3 border-bottom">
  <h2>Objective新規作成</h2>
</div>

<div>
  <%= render 'form', ambition: @ambition %>
</div>

app/views/ambitions/show.html.erb
<div class="text-center pb-4 mb-3 border-bottom">
  <h2>OKR詳細</h2>
</div>

<div>
  ・Ovjective内容
</div>
<div>
  <%= @ambition.content %>
</div>
<div class="row border-bottom justify-content-end mb-2">
  <div class="col-2">
    <%= link_to '編集', edit_ambition_path, class: 'd-inline-block' %>
  </div>
  <div class="col-2">
    <%= link_to '削除', ambition_path, method: :delete, data: { confirm: "本当に削除しますか？" }, class: 'd-inline-block' %>
  </div>
</div>

<table class="table mb-5">
  <tr>
    <td>
      開始日
    </td>
    <td>
    </td>
    <td>
      終了日
    </td>
  </tr>
  <tr>
    <td>
      <%= @ambition.start_date %>
    </td>
    <td>
      〜
    </td>
    <td>
      <%= @ambition.end_date %>
    </td>
  </tr>
</table>

<div>
  <%= render '/key_results/index', ambition: @ambition %>
</div>

<div class="row justify-content-center mb-5">
  <div class="col-4">
   <%= link_to 'Key_Resultを追加', "/ambitions/#{@ambition.id}/key_results/new", class: "btn btn-primary btn-block" %>
  </div>
</div>