config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  
  get 'signup', to: 'users#new'
  resources :users, only:[:show, :new, :create, :edit, :update]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :ambitions, only:[:show, :new, :create, :edit, :update, :destroy]
  
  get '/ambitions/:id/key_results/new', to: 'key_results#new'
  resources :key_results, only:[:create, :edit, :update, :destroy]
  
  get '/key_results/:id/daily_results/new', to: 'daily_results#new'
  resources :daily_results, only:[:create, :edit, :update, :destroy]
end

app/models/key_result.rb
class KeyResult < ApplicationRecord
  belongs_to :ambition
  
  validates :content, presence: true, length: { maximum: 255 }
  validates :numerical_goal, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than: 500 }

  has_many :daily_results, dependent: :destroy
end

app/controllers/key_results_controller.rb
class KeyResultsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:edit, :update, :destroy]
  
  def new
    @ambition = Ambition.find(params[:id])
    @key_result = @ambition.key_results.build
  end

  def create
    @ambition = Ambition.find(params[:ambition_id])
    @key_result = @ambition.key_results.build(key_result_params)
    if @key_result.save
      flash[:success] = 'Key Resultの作成に成功しました'
      redirect_to @ambition
    else
      flash[:danger] = 'Key Resultの作成に失敗しました'
      render :new
    end
  end

  def edit
  end

  def update
    if @key_result.update(key_result_params)
      flash[:success] = 'Key Resultの保存に成功しました'
      redirect_to @ambition
    else
       flash[:danger] = 'Key Resultの保存に失敗しました'
      render :edit
    end
  end

  def destroy
    @key_result.destroy
    flash[:success] = 'Key Resultを削除しました'
    redirect_to @ambition
  end
  
  private
  
  def key_result_params
    params.require(:key_result).permit(:content, :numerical_goal)
  end
  
  def correct_user
    @key_result = KeyResult.find(params[:id])
    @ambition = @key_result.ambition
    unless current_user.id == @ambition.user_id
      flash[:danger] = "権限がありません"
      redirect_to root_url
    end
  end
end

app/views/key_results/_form.html.erb
<%= form_with(model: key_result, local: true) do |f| %>
<%= hidden_field_tag :ambition_id, ambition.id %>
<%= render 'layouts/error_messages', model: f.object %>
<div class="row">
  <div class="col-sm-4">
    <p>Objective</p>
  </div>
  <div class="col-sm-8">
    <%= ambition.content %>
  </div>
  <div class="col-sm-4">
    <p>Key_Result</p>
  </div>
  <div class="col-sm-8 form-group">
    <%= f.text_area :content, class: 'form-control', rows: 6 %>
  </div>
</div>
<div class="row">
  <div class="col-sm-4">
    <p>目標数値</p>
    <p>（半角数値）</p>
  </div>
  <div class="col-sm-8 form-group">
    <%= f.number_field :numerical_goal, class: 'form-control' %>
  </div>
</div>
<div class="row justify-content-center mb-5">
  <div class="col-4">
    <%= f.submit '保存', class: 'btn btn-primary btn-block' %>
  </div>
</div>
<% end %>

app/views/key_results/_index.html.erb
<% ambition.key_results.each do |key_result| %>
<div>
  <div>
    ・Key Result内容
  </div>
  <div>
    <%= key_result.content %>
  </div>
  <div class="row border-bottom justify-content-end mb-2">
    <div class="col-2">
      <%= link_to '評価', "/key_results/#{key_result.id}/daily_results/new", class: 'd-inline-block' %>
    </div>
    <div class="col-2">
      <%= link_to '編集', edit_key_result_path(key_result), class: 'd-inline-block' %>
    </div>
  </div>
  
  <table class="table">
    <tr>
      <td>
        目標数値
      </td>
      <td>
        達成数値
      </td>
      <td>
        達成率
      </td>
    </tr>
    <tr>
      <td>
        <%= key_result.numerical_goal %>
      </td>
      <td>
        <% unless key_result.daily_results.first == nil %>
        <%= key_result.daily_results.order(result_date: :desc).first.result %>
        <% end %>
      </td>
      <td>
        <% unless key_result.daily_results.first == nil %>
        <%= key_result.daily_results.order(result_date: :desc).first.result * 100 / key_result.numerical_goal %> %
        <% end %>
      </td>
    </tr>
  </table>
</div>

<div class="pb-4">
  評価履歴
  <%= render '/daily_results/index', key_result: key_result %>
</div>
<% end %>

app/views/key_results/_key_result_form.html.erb
<%= form_with(model: key_result, local: true) do |f| %>
<%= hidden_field_tag :ambition_id, ambition.id %>
<%= render 'layouts/error_messages', model: f.object %>
<div class="row">
  <div class="col-sm-4">
    <p>Objective</p>
  </div>
  <div class="col-sm-8">
    <%= ambition.content %>
  </div>
  <div class="col-sm-4">
    <p>Key_Result</p>
  </div>
  <div class="col-sm-8 form-group">
    <%= f.text_area :content, class: 'form-control', rows: 6 %>
  </div>
</div>
<div class="row">
  <div class="col-sm-4">
    <p>目標数値</p>
    <p>（半角数値）</p>
  </div>
  <div class="col-sm-8 form-group">
    <%= f.number_field :numerical_goal, class: 'form-control' %>
  </div>
</div>
<div class="text-center">
<%= f.submit '保存', class: 'btn btn-primary btn-lg' %>
</div>
<% end %>

app/views/key_results/edit.html.erb
<div class="row pb-4 mb-3 border-bottom">
  <div class="col-sm-2">
    <%= link_to '戻る', ambition_path(@key_result.ambition) %>
  </div>
  <div class="col-sm-8 text-center">
    <h2>Key_Result編集・削除</h2>
  </div>
  <div class="col-sm-2 text-center">
    <%= link_to '削除', key_result_path, class: 'btn btn-danger btn-sm', method: :delete, data: { confirm: "本当に削除しますか？" } %>
  </div>
</div>

<div>
  <%= render 'form', ambition: @ambition, key_result: @key_result %>
</div>

app/views/key_results/new.html.erb
<div class="text-center pb-4 mb-3 border-bottom">
  <h2>Key_Result新規作成</h2>
</div>

<div>
  <%= render 'form', ambition: @ambition, key_result: @key_result %>
</div>