config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  
  get 'signup', to: 'users#new'
  resources :users, only:[:show, :new, :create, :edit, :update]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :ambitions, only:[:show, :new, :create, :edit, :update, :destroy]
  
  get '/ambitions/:id/key_results/new', to: 'key_results#new'
  resources :key_results, only:[:create, :edit, :update, :destroy]
  
  get '/key_results/:id/daily_results/new', to: 'daily_results#new'
  resources :daily_results, only:[:create, :edit, :update, :destroy]
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
<div id="error_explanation" class="alert alert-warning">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li>
      <%= message %>
    </li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>

<div class="alert alert-<%= message_type %>">
  <%= message %>
</div>

<% end %>
  

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-light bg-light">
    <a class="navbar-brand" href="/">WhyDo</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#NavItemContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse justify-content-end" id="NavItemContent">
    <ul class="navbar-nav">
      <% if logged_in? %>
      <li class="nav-item"><%= link_to 'OKR新規作成', new_ambition_path, class: "nav-link" %></li>
      <li class="nav-item"><%= link_to current_user.name.to_s + '’sページ', user_path(current_user), class: "nav-link" %></li>
      <li class="nav-item"><%= link_to 'ログアウト', logout_path, method: :delete, class: "nav-link" %></li>
      <% else %>
      <li class="nav-item"><%= link_to '新規登録', signup_path, class: "nav-link" %></li>
      <li class="nav-item"><%= link_to 'ログイン', login_path, class: "nav-link" %></li>
      <% end %>
    </ul>
    </div>
    
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=devise-width, initial-scale=1, shrink-to-fit=no">
    <title>Whydo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      
      <%= yield %>
    </div>
  </body>
</html>